//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FenetreGenerateurMenus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FenetreGenerateurMenus() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.FenetreGenerateurMenus", typeof(FenetreGenerateurMenus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher les images des plats ?.
        /// </summary>
        public static string AfficherImage {
            get {
                return ResourceManager.GetString("AfficherImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un déjeuner.
        /// </summary>
        public static string Dejeuner {
            get {
                return ResourceManager.GetString("Dejeuner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un diner/souper.
        /// </summary>
        public static string DinerSouper {
            get {
                return ResourceManager.GetString("DinerSouper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Générer.
        /// </summary>
        public static string Generer {
            get {
                return ResourceManager.GetString("Generer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations préalables à la génération.
        /// </summary>
        public static string InfoGeneration {
            get {
                return ResourceManager.GetString("InfoGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ingrédients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un jour.
        /// </summary>
        public static string Jour {
            get {
                return ResourceManager.GetString("Jour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste d&apos;épicerie.
        /// </summary>
        public static string ListeEpicerie {
            get {
                return ResourceManager.GetString("ListeEpicerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menus.
        /// </summary>
        public static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir un menu existant.
        /// </summary>
        public static string OuvrirMenu {
            get {
                return ResourceManager.GetString("OuvrirMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Période :.
        /// </summary>
        public static string Periode {
            get {
                return ResourceManager.GetString("Periode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnes :.
        /// </summary>
        public static string Personnes {
            get {
                return ResourceManager.GetString("Personnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regénérer le plat.
        /// </summary>
        public static string RegenererPlat {
            get {
                return ResourceManager.GetString("RegenererPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder le menu.
        /// </summary>
        public static string SauvegarderMenu {
            get {
                return ResourceManager.GetString("SauvegarderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une semaine.
        /// </summary>
        public static string Semaine {
            get {
                return ResourceManager.GetString("Semaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Breuvage.
        /// </summary>
        public static string SeparateurBreuvage {
            get {
                return ResourceManager.GetString("SeparateurBreuvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déjeuner.
        /// </summary>
        public static string SeparateurDejeuner {
            get {
                return ResourceManager.GetString("SeparateurDejeuner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déssert.
        /// </summary>
        public static string SeparateurDessert {
            get {
                return ResourceManager.GetString("SeparateurDessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrée.
        /// </summary>
        public static string SeparateurEntree {
            get {
                return ResourceManager.GetString("SeparateurEntree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jour.
        /// </summary>
        public static string SeparateurJour {
            get {
                return ResourceManager.GetString("SeparateurJour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plat principal.
        /// </summary>
        public static string SeparateurPlatPrincipal {
            get {
                return ResourceManager.GetString("SeparateurPlatPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivi des plats non admissibles.
        /// </summary>
        public static string SuiviNonAdmissible {
            get {
                return ResourceManager.GetString("SuiviNonAdmissible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nutritia - Génération de menus.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez remplir la section Informations préalables à la génération et appuyer sur le bouton Générer pour générer un menu. Lors de l&apos;appuie sur le bouton, le menu apparaîtra..
        /// </summary>
        public static string TooltipNonAdmissible {
            get {
                return ResourceManager.GetString("TooltipNonAdmissible", resourceCulture);
            }
        }
    }
}
